### PR TITLE
OPSEXP-2627 Update release section with ecosystem updates

### PR DESCRIPTION
**Pull request by gionn**

### CODE REVIEW

**Review by pmacius — APPROVED** [review]

**Review by alxgomz — COMMENTED** [review]
I'm not convinced we should do that just with the release PR.

**Comment by gionn** [comment]
> I'm not convinced we should do that just with the release PR.

as a reminder for the worst case, because if we are not actively adding new feature in the playbook we are never gonna merge dependency updates

**Comment by alxgomz** [comment]
> > I'm not convinced we should do that just with the release PR.
> 
> as a reminder for the worst case, because if we are not actively adding new feature in the playbook we are never gonna merge dependency updates

Yes I understand the motivation but bumping libs more or less blindly just before release sounds risky. Maybe we should be more diligent in reviewing dependabot pr BEFORE testing week instead.

**Comment by gionn** [comment]
our test coverage is pretty high here, I've zero concerns merging dependencies if build is green. Most of them are actually just test dependencies and would not impact the end users.

**Review by alxgomz — APPROVED** [review]

**Pull request merged**
