### PR TITLE
OPSEXP-1172 fix hardcoded templates

### LINKED ISSUE #219: .sh files with setenv path hard coded
Hi,

It is detected that the following "sh" boot files have the path of the "setenv.sh" hard coded without using the ansible configuration path {{ config_folder }}.

The following change is proposed
```bash
## original
. /etc/opt/alfresco/setenv.sh
## change
. {{ config_folder }}/setenv.sh
```

Affected files
- alfresco-ansible-deployment\roles\sfs\templates\ats-shared-fs.sh
- alfresco-ansible-deployment\roles\sync\templates\syncservice.sh
- alfresco-ansible-deployment\roles\transformers\templates\ats-ate-aio.sh
- alfresco-ansible-deployment\roles\trouter\templates\ats-atr.sh

### PR DESCRIPTION
**Pull request by gionn**
ref OPSEXP-1112
fix #219

### CODE REVIEW

**Comment by alxgomz** [comment]
we also have a bunch of pytest script which still have those hardcoded values:
* ./roles/repository/molecule/default/tests/test_repository.py
* ./roles/sfs/molecule/default/tests/test_sfs.py
* ./roles/trouter/molecule/default/tests/test_trouter.py
and. also a molecule playbook:
* ./roles/repository/molecule/default/converge.yml
and maybe others

**Review by alxgomz — CHANGES_REQUESTED** [review]
there are more occurrences of these hardcoded strings

**Comment by gionn** [comment]
> we also have a bunch of pytest script which still have those hardcoded values:

it may be better to keep tests unlinked from defaults defined in roles, I would expect tests failure after changing a variable containing a path rather than all green tests.

**Review by alxgomz — APPROVED** [review]
LGTM

**Pull request merged**
