### PR TITLE
OPSEXP-865: port defatultvars

### PR DESCRIPTION
**Pull request by alxgomz**
move hardcoded port numbers to common/defaults/main.yml and make them variables (which can be set later down the road) and default to numeric values when not set.
tests have not been updated because:
* I couldn't find a way to tell the molecule[docker] driver to use a variable in its config (`exposed_ports`)
* tests are anyway connecting to the `published_ports` which is unrelated to the ports pods actually listen on, and are set statically in the molecule[docker] `platform` config

### CODE REVIEW

**Review by sergiuv2020 — COMMENTED** [review]
Could you please also remove the hardcodings in the prerequisites checks. It should be ok to just import the default vars from common before everything.

**Review by gavincornwell — COMMENTED** [review]
Nothing more to add that hasn't been said already, looks good.

**Review by nilsSure — APPROVED** [review]
LGTM

**Comment by alxgomz** [comment]
> Could you please also remove the hardcodings in the prerequisites checks. It should be ok to just import the default vars from common before everything.

Done. I also had to add a retry mecanism as I had issues with the check mecanism when consecutives tasks test the same port from different hosts.

**Pull request merged**
