### PR TITLE
OPSEXP-1296 Drop support for centos8 in ansible

### PR DESCRIPTION
**Pull request by himanshu-nigam**
Drop support for centos8

### CODE REVIEW

**Review by gionn — CHANGES_REQUESTED** [review]
there are some specific files that needs to be removed as well, like https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/roles/common/vars/CentOS8.yml

**Comment by himanshu-nigam** [comment]
Remove centos8.yml

**Review by alxgomz — CHANGES_REQUESTED** [review]
postgres & transformers roles also contain var files dedicated to Centos8 that need to be removed

**Review by alxgomz — APPROVED** [review]
LGTM

**Review by gionn — APPROVED** [review]

**Pull request merged**
